// client/App.vue
<template>
  <div class="px-4 lg:px-0 max-w-7xl mx-auto py-12">
    <h1 class="font-bold text-2xl">Hello, world!</h1>
    <section class="mt-4">
      <p class="text-gray-500">
        This is a starter template for a Vue.js app with Tailwind CSS
        and TypeScript. ⚡️
      </p>
    </section>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'App',
});
</script>

// client/App.tsx
export default function App() {
    return (
        <div className="px-4 lg:px-0 max-w-7xl mx-auto py-12">
            <h1 className="font-bold text-2xl">Hello, world!</h1>
            <section className="mt-4">
                <p className="text-gray-500">
                    This is a starter template for a React app with Tailwind CSS
                    and TypeScript. ⚡️
                </p>
            </section>
        </div>
    )
}
